[package]
name = "ffxiv-otp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
totp-rs = "5.7"
reqwest = { version = "0.12", features = ["blocking"] }
xdg = "3.0"
base32 = "0.5"
